trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
- job: 'Build'
  displayName: 'Build job'
  steps:
  - script: echo Building $(solution) with $(buildConfiguration) configuration
    displayName: 'Build solution'

- job: 'Deploy'
  displayName: 'Deploy job'
  dependsOn: Build
  condition: succeeded('Build')
  steps:
  - script: echo Deploying to production
    displayName: 'Deploy to production'
