# Azure Pipeline YAML to build and deploy Terraform

trigger:
- master  # Trigger pipeline on changes to the main branch. Adjust as needed.

pool:
  vmImage: 'ubuntu-latest'  # Use an Ubuntu agent

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # Use Python 3.x, required for Terraform

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt  # If you have any Python dependencies
  displayName: 'Install dependencies'  # Change as needed

- script: |
    terraform init  # Initialize Terraform
  displayName: 'Terraform init'

- script: |
    terraform validate  # Validate Terraform configuration
  displayName: 'Terraform validate'

- script: |
    terraform plan -out=tfplan  # Generate Terraform plan
  displayName: 'Terraform plan'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(Build.ArtifactStagingDirectory)
    artifact: 'terraform_plan'

- script: |
    terraform apply -auto-approve tfplan  # Apply Terraform changes
  displayName: 'Terraform apply'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(Build.ArtifactStagingDirectory)
    artifact: 'terraform_state'

# Add additional steps for deploying the infrastructure or testing as needed.
